/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import java.awt.Color;
import javax.swing.JFrame;
import persistence.ManagerFactoryRepository;

/**
 *
 * @author copad
 */
public class window extends javax.swing.JFrame {
    private ManagerFactoryRepository managerFactory;
    /** 
     * Creates new form window
     */
    public window(ManagerFactoryRepository managerFactory) {
        initComponents();
        this.setTitle("Menu");
        this.managerFactory=managerFactory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonCategory = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonSale = new javax.swing.JButton();
        Costumer = new javax.swing.JButton();
        BotonProvider = new javax.swing.JButton();
        Costumer1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonCategory.setText("Provider");
        BotonCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCategoryActionPerformed(evt);
            }
        });

        jButton2.setText("Product");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonSale.setText("Sale");
        jButtonSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaleActionPerformed(evt);
            }
        });

        Costumer.setText("Costumer");
        Costumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostumerActionPerformed(evt);
            }
        });

        BotonProvider.setText("Category");
        BotonProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProviderActionPerformed(evt);
            }
        });

        Costumer1.setText("SaleItem");
        Costumer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Costumer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonProvider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSale, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Costumer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Costumer1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(BotonProvider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Costumer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Costumer1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProviderActionPerformed
        windowCategory frame = new windowCategory(managerFactory);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_BotonProviderActionPerformed

    private void BotonCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCategoryActionPerformed
        windowProvider provider = new windowProvider(managerFactory);

        provider.setVisible(true);
        provider.setLocationRelativeTo(null);
        provider.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_BotonCategoryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        windowProduct product=new windowProduct(managerFactory);
        
        product.setVisible(true);
        product.setLocationRelativeTo(null);
        product.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaleActionPerformed
       windowSale sale=new windowSale(managerFactory);
       sale.setVisible(true);
       sale.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       sale.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonSaleActionPerformed

    private void CostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostumerActionPerformed
        
        windowCostumer costumer=new windowCostumer(managerFactory);
        costumer.setVisible(true);
        costumer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        costumer.setLocationRelativeTo(null);
    }//GEN-LAST:event_CostumerActionPerformed

    private void Costumer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Costumer1ActionPerformed
        windowSaleItem saleItem=new windowSaleItem(managerFactory);
        saleItem.setVisible(true);
        saleItem.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        saleItem.setLocationRelativeTo(null);
    }//GEN-LAST:event_Costumer1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCategory;
    private javax.swing.JButton BotonProvider;
    private javax.swing.JButton Costumer;
    private javax.swing.JButton Costumer1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSale;
    // End of variables declaration//GEN-END:variables
}
